12:23:16 AM:DEBUG [conexion.py:26] Conexión exitosa: <connection object at 0x0000026AA9825CF0; dsn: 'user=postgres password=xxx dbname=contrurent host=127.0.0.1 port=5432', closed: 0>
